modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="github.com/kosma/sqlite-jdbc/issues"
license="All rights reserved"

[[mods]]
modId="sqlite_jdbc"
version="3.36.0.3"
displayName="SQLite JDBC"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sqlite-jdbc"
logoFile="icon.png"
authors="xerial, Kosmolot"
description='''SQLite JDBC Driver for Fabric and Forge'''
