modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/kosma/sqlite-jdbc/issues"
license="Apache"

[[mods]]
modId="sqlite_jdbc"
version="${version}"
displayName="SQLite JDBC"
displayURL="https://www.curseforge.com/minecraft/mc-mods/sqlite-jdbc"
logoFile="icon.png"
authors="xerial, Kosmolot"
description='''SQLite JDBC Driver for Fabric and Forge'''
