modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="examplemod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="SQLite JDBC" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://kosma.pl/" #optional
#logoFile="logo.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="xerial, Kosmolot" #optional
description='''SQLite JDBC Driver'''
